[tools]
bun = "latest"
delta = "latest"
gcloud = "latest"
gh = "latest"
"github:getsentry/XcodeBuildMCP" = "latest"
"github:stablyai/agent-slack" = "latest"
herdr = "latest"
lazygit = "latest"
node = "24"
opencode = "latest"
"npm:@bitkyc08/opencodex" = "2.12.0"
python = "3.13"
starship = "latest"
yazi = "latest"

[env]
CLOUDSDK_PYTHON = "{{env.HOME}}/.local/share/mise/installs/python/3.13/bin/python3"
